// Radio Vostok track list — files live in public/audio/radio and are
// served as static assets from the Cloudflare deployment.
export type RadioTrack = {
  id: string;
  title: string;
  score: string | null;
  file: string;
};

export const trackSrc = (track: RadioTrack) => `/audio/radio/${encodeURIComponent(track.file)}`;

export const radioTracks: RadioTrack[] = [
  { id: "01", title: "BJ Lips - Love Potion", score: "10/10", file: "01_bj_lips.m4a" },
  { id: "02", title: "Love Potions X Track 10", score: "11/10", file: "02_love_potions_x_track_10.m4a" },
  { id: "03", title: "Ecstasy (Remix)", score: "10/10", file: "03_ecstasy_remix.m4a" },
  { id: "04", title: "Love Potions x I'll Do It", score: "7/10", file: "04_love_potions_x_ill_do_it.m4a" },
  { id: "05", title: "Voruyu alkogol (Slowed + Reverb)", score: "8/10", file: "05_voruyu_alkogol_slowed_reverb.m4a" },
  { id: "06", title: "ROMANCEPLANET w/ STAKILLAZ", score: "10/10", file: "06_romanceplanet_w_stakillaz.m4a" },
  { id: "07", title: "BABYDOLL", score: "6/10", file: "07_babydoll.m4a" },
  { id: "08", title: "MY JEALOUSY (Slowed)", score: "10/10", file: "08_my_jealousy_slowed.m4a" },
  { id: "09", title: "Love Potions x Tipsy (Slowed)", score: "9/10", file: "09_love_potions_x_tipsy.m4a" },
  { id: "10", title: "Mariah Carey - Obsessed (fvckaron audio)", score: "9/10", file: "10_glamorgeddon_slowed.m4a" },
  { id: "11", title: "glamorgeddon (Slowed)", score: "5/10", file: "11_mariah_carey_obsessed_fvckaron_audio_slowed_reverb.m4a" },
  { id: "12", title: "Tears/Lipgloss (Remix)", score: "6/10", file: "12_tears_lipgloss_remix.m4a" },
  { id: "13", title: "Britney Manson - FASHION (Slowed)", score: "7/10", file: "13_britney_manson_fashion_slowed.m4a" },
  { id: "14", title: "Shy Smith - Soaked", score: "5/10", file: "14_shy_smith_soaked_slowed_reverb.m4a" },
  { id: "15", title: "Love Potions X MY JEALOUSY - bjlips & vivibaby", score: "9/10", file: "15_Love_Potions_X_MY_JEALOUSY_-_bjlips_&_vivibaby_(mashup).m4a" },
  { id: "16", title: "INTERSTELLAR ULTRAFUNK - SLOWED", score: "NR", file: "16_INTERSTELLAR_ULTRAFUNK_-_SLOWED.m4a" },
  { id: "17", title: "bj lips, princess paparazzi - love potions", score: "10/10", file: "17_Love_Potions_(6arelyhuman_Remix).m4a" },
  { id: "18", title: "Snow Strippers x Adore x Crystal Castles type beat - 'sleez'", score: "6/10", file: "18_Snow_Strippers_x_Adore_x_Crystal_Castles_type_beat_-_'sleez'.m4a" },
  { id: "19", title: "Charli xcx - b2b (qyurisuu remix)", score: "6/10", file: "19_Charli_xcx_-_b2b_(qyurisuu_remix).m4a" },
  { id: "20", title: "2000 (slowed)", score: "7/10", file: "20_2000_(slowed).m4a" },
  { id: "21&", title: "Schleini - Liebe (Techno)", score: "8/10", file: "21&_Schleini_-_Liebe_(Techno).m4a" },
  { id: "22", title: "TENSA (Ultra Slowed)", score: "10/10", file: "22_TENSA_(Ultra_Slowed).m4a" },
  { id: "23&", title: "Big Boogie - Kush Breath", score: "9/10", file: "23&_Big_Boogie_-_Kush_Breath_(Official_Music_Video).m4a" },
  { id: "24", title: "me pierdo", score: "8/10", file: "24_me_pierdo.m4a" },
  { id: "25&", title: "Habits (Stay High) x Stereo Love", score: "10/10", file: "25&_Habits_(Stay_High)_x_Stereo_Love_(slowed_to_perfection).m4a" },
  { id: "26", title: "Saxo Funk (Super Slowed)", score: "NR", file: "26Saxo_Funk_(Super_Slowed).m4a" },
  { id: "27", title: "Lost Sky - Fearless (Ultra Slowed + Reverb)", score: "NR", file: "27_𝗟𝗼𝘀𝘁_𝗦𝗸𝘆_-_𝗙𝗲𝗮𝗿𝗹𝗲𝘀𝘀_(Ultra_Slowed__Reverb).m4a" },
  { id: "28", title: "TIKI TIKI", score: "NR", file: "28_TIKI_TIKI.m4a" },
  { id: "29", title: "THUNDER (Super Slowed)", score: "NR", file: "29_THUNDER_(Super_Slowed).m4a" },
  { id: "30", title: "Bad Romance // Best Part Only // Slowed + Reverb", score: "NR", file: "30_bad_romance__best_part_only__slowed__reverb.m4a" },
  { id: "31", title: "Kavkaz (slowed+reverb)", score: "NR", file: "31_Kavkaz_(slowedreverb).m4a" },
  { id: "32", title: "Versatile (Hardstylish Remix Slowed)", score: "NR", file: "32_Versatile_(Hardstylish_Remix_Slowed).m4a" },
  { id: "33", title: "You got it (jersey club)", score: "NR", file: "33_You_got_it_(jersey_club).m4a" },
  { id: "34", title: "PortwaveShadow lady Slowed Reverb", score: "NR", file: "34_PortwaveShadow_lady_Slowed_Reverb.m4a" },
  { id: "35", title: "And I Have Come for You", score: "NR", file: "35_And_I_Have_Come_for_You.m4a" },
  { id: "36", title: "VIDA NOTURNA (Slowed + Reverb)", score: "NR", file: "36_VIDA_NOTURNA_(Slowed_Reverb).m4a" },
  { id: "37", title: "Atmosphere", score: "NR", file: "37_KNSRK_-_Atmosphere_(Slowed__Reverb).m4a" },
  { id: "38", title: "Hoes Come Easy", score: "NR", file: "38_Hoes_Come_Easy_(Slowed__Low_Honor_-_The_Dark_Triad).m4a" },
  { id: "39", title: "Leanin - Cornell", score: "NR", file: "39_Leanin.m4a" },
  { id: "40", title: "Travis Scott - DUMBO (Instrumental)", score: "NR", file: "40_Travis_Scott_-_DUMBO_(Instrumental).m4a" },
  { id: "41", title: "specialsadism (super slowed)", score: "NR", file: "41_specialsadism_(super_slowed).m4a" },
  { id: "42", title: "Gangnam Style x Give Me Everything (Slowed & Reverb)", score: "NR", file: "42_Gangnam_Style_x_Give_Me_Everything_(Slowed_&_Reverb)_(TikTok_Version).m4a" },
  { id: "43", title: "BLAULICHT HARDTEKK", score: "NR", file: "43_BLAULICHT_HARDTEKK.m4a" },
  { id: "44", title: "I WAS MADE FOR LOVIN' YOU (Slowed)", score: "NR", file: "44_I_WAS_MADE_FOR_LOVIN'_YOU_(Slowed).m4a" },
  { id: "45", title: "UMBASA - NERO (Super Slowed + Reverb)", score: "NR", file: "45_UMBASA_-_NERO_(Super_Slowed_+_reverb).m4a" },
  { id: "46", title: "down on me x I mean it", score: "NR", file: "46_down_on_me_x_I_mean_it.m4a" },
  { id: "47", title: "Strippers", score: "NR", file: "47_Strippers.m4a" },
  { id: "48", title: "Griddle (feat. Don Toliver)", score: "NR", file: "48_Griddle_(feat._Don_Toliver).m4a" },
  { id: "49", title: "Yo Voy - Lil Uzi Vert (unreleased)", score: "NR", file: "49_Yo_Voy_-_Lil_Uzi_Vert_(unreleased).m4a" },
  { id: "50", title: "(FREE) twentythree + 2013club + swag type beat - money walk", score: "NR", file: "50_(FREE)_twentythree_+_2013club_+_swag_type_beat_-_money_walk.m4a" },
  { id: "51", title: "Antiflvx - White Light", score: "NR", file: "51_Antiflvx_-_White_Light.m4a" },
  { id: "52", title: "The Way I Are (slowed to perfection)", score: "NR", file: "52_The_Way_I_Are_(slowed_to_perfection).m4a" },
  { id: "53", title: "VOCE NA MIRA (Super Slowed)", score: "NR", file: "53_VOCE_NA_MIRA_(Super_Slowed).m4a" },
  { id: "54", title: "Take Me There - DA TI", score: "NR", file: "54_Take_Me_There_-_DA_TI_(Lyrics).m4a" },
  { id: "55", title: "Templar (Versions) (Super Slowed)", score: "NR", file: "55_Templar_(Versions)_(Super_Slowed).m4a" },
  { id: "56", title: "The Haunted Youth - Coming Home", score: "NR", file: "56_The_Haunted_Youth_-_Coming_Home.m4a" },
  { id: "57", title: "HERO! - Sped Up", score: "NR", file: "57_HERO!_-_Sped_Up.m4a" },
  { id: "58", title: "OBLXKQ, eyfect, +w - Untitled#39", score: "NR", file: "58_OBLXKQ_eyfect_w_Untitled39.m4a" },
  { id: "59", title: "Criminal x Love Potions", score: "NR", file: "59_Criminal_x_Love_Potions.m4a" },
  { id: "60", title: "You Could Be The One [Slowed To Perfection] Snow Strippers", score: "NR", file: "60_You_Could_Be_The_One_[Slowed_To_Perfection]_Snow_Strippers.m4a" },
  { id: "61", title: "Porter Robinson - Mirror", score: "NR", file: "61_Porter_Robinson_-_Mirror_(Official_Music_Video)_4.m4a" },
  { id: "62", title: "Feel So Close (Best Part Slowed)", score: "NR", file: "62_Feel_So_Close_(Best_Part_Slowed).m4a" },
  { id: "63", title: "worry (ultra slowed)", score: "NR", file: "63_worry_(ultra_slowed).m4a" },
  { id: "64", title: "New Jeans Jersey Remix (Miside Mita Edit TikTok Version)", score: "NR", file: "64_New_Jeans_Jersey_Remix_(Audio_Edited)_(Miside_Mita_Edit_TikTok_Version)_[made_by_purple_drip_boy]_4.m4a" },
  { id: "65", title: "SIMULVCRUM - Silent Love (Slowed)", score: "NR", file: "65_Silent_Love_(Slowed).m4a" },
  { id: "66", title: "ravyn, CLINCE, winter - CELESTIA (Slowed)", score: "NR", file: "66_CELESTIA_(Slowed).m4a" },
  { id: "67", title: "CLARITY - HARDSTYLE (AGARTHA EDIT)", score: "NR", file: "67_CLARITY_-_HARDSTYLE_(AGARTHA_EDIT).m4a" },
  { id: "68", title: "T3NZU - Under The Influence", score: "NR", file: "68_T3NZU_-_Under_The_Influence.m4a" },
  { id: "69", title: "Kenia Os - Tu y Yo X Siempre", score: "NR", file: "69_Kenia_Os_-_Tú_y_Yo_X_Siempre_(Lyric_Video).m4a" },
  { id: "70", title: "Ayesha Erotica, Mo Beats - Yummy (Righteous Remix - Sped Up)", score: "NR", file: "70_Yummy_(Righteous_Remix_-_Sped_Up)_4.m4a" },
  { id: "71", title: "Embers (Slowed)", score: "NR", file: "71_Embers_(Slowed).m4a" },
  { id: "72", title: "Irokz - Angel (Sped Up)", score: "NR", file: "72_Angel_(Sped_Up)_[ZTiaysiWjVE].m4a" },
  { id: "73", title: "Blurred Stars", score: "NR", file: "73_Blurred_Stars.m4a" },
  { id: "74", title: "Jeff Germita - IM SO LUCKY JUMPSTYLE (Super Slowed)", score: "NR", file: "74_IM_SO_LUCKY_JUMPSTYLE_(Super_Slowed).m4a" },
  { id: "75", title: "Nostalgia", score: "NR", file: "75_Nostalgia.m4a" },
  { id: "76", title: "2hollis - poster boy (slowed + reverb) lyrics", score: "NR", file: "76_2hollis_-_poster_boy_(slowed__reverb)_lyrics.m4a" },
  { id: "77", title: "Close Your Eyes and Make a Wish - Fright Night (Slowed)", score: "NR", file: "77_Close_Your_Eyes_and_Make_a_Wish_-_Fright_Night_(Slowed).m4a" },
  { id: "78", title: "lustr - tell me (lyrics)", score: "NR", file: "78_lustr_-__tell_me_(lyrics).m4a" },
  { id: "79", title: "UNDONE", score: "NR", file: "79_UNDONE.m4a" },
  { id: "80", title: "FUNERAL", score: "NR", file: "80_FUNERAL.m4a" },
  { id: "81", title: "Desire (Hucci Remix)", score: "NR", file: "81_Desire_(Hucci_Remix)_4.m4a" },
  { id: "82", title: "BLOODY MARY - VØIDGLiTCH & ØNELY", score: "NR", file: "82_BLOODY_MARY_-_VØIDGLiTCH_&_ØNELY.m4a" },
  { id: "83", title: "Tart, Andreea Flavia - Stereo Love", score: "NR", file: "83_Tart,_Andreea_Flavia_-_Stereo_Love.m4a" },
  { id: "84", title: "Poker Face X Vacation Bible School - Ayesha Erotica & Lady Gaga (mashup)", score: "NR", file: "84_Poker_Face_X_Vacation_Bible_School_-_Ayesha_Erotica_&_Lady_Gaga_(mashup).m4a" },
  { id: "85", title: "SHAED - Trampoline (Jauz Remix)", score: "NR", file: "85_SHAED_-_Trampoline_(Jauz_Remix).m4a" },
  { id: "86", title: "SAILXNCE - ACTION", score: "NR", file: "86_SAILXNCE_-_ACTION.m4a" },
  { id: "87", title: "OXWAVE - korabli", score: "NR", file: "87_OXWAVE_-_korabli.m4a" },
  { id: "88", title: "SORYN - IDLE [hardwave/phonk]", score: "NR", file: "88_SORYN_-_IDLE_[hardwave_phonk]_-_Soryn_(youtube).m4a" },
  { id: "89", title: "Kxllswxtch - WASTE [PHNK REMIX]", score: "NR", file: "89_Kxllswxtch_-_WASTE_[PHNK_REMIX]_-_PHONKmedia東京_(youtube).m4a" },
  { id: "90", title: "VØJ, .diedlonely, énoument, GOTHBOY - Last Thought Before Shutdown", score: "NR", file: "90_VØJ,_.diedlonely,_énoument,_GOTHBOY_-_Last_Thought_Before_Shutdown_(4K_Official_Music_Video)_-_GOTHBOY_(youtube).m4a" },
  { id: "91", title: "YEAT - Percz", score: "NR", file: "91_YEAT_-_Percz_(prod._SKY)_-_SKY_(youtube).m4a" },
  { id: "92", title: "studio killers - jenny (slowed + reverb)", score: "NR", file: "92_studio_killers_-_jenny_(slowed_+_reverb)_-_vierra_(youtube).m4a" },
  { id: "93", title: "Devi McCallion - I WANT THINGS TO BE BEAUTIFUL", score: "NR", file: "93_Devi_McCallion_-_I_WANT_THINGS_TO_BE_BEAUTIFUL_-_Devi_McCallion_(youtube).m4a" },
  { id: "94", title: "All Aboard - Yelawolf", score: "NR", file: "94_All_Aboard_-_Yelawolf_(youtube).m4a" },
  { id: "95", title: "SAKUREYE - IN YOUR EYES / Extended", score: "NR", file: "95_SAKUREYE_-_IN_YOUR_EYES___Extended_-_S.P_(youtube).m4a" },
  { id: "96", title: "Popstar (Yokimo Remix)", score: "NR", file: "96_Popstar_(Yokimo_Remix)_-_Kill_Eva_(youtube).m4a" },
  { id: "97", title: "Dirty - Hit Da Floe", score: "NR", file: "97_Dirty_-_Hit_Da_Floe_-_DirtyVEVO_(youtube).m4a" },
  { id: "98", title: "I'm Miles Morales - lovin", score: "NR", file: "98_I'm_Miles_Morales_-_lovin_(youtube).m4a" },
  { id: "99", title: "Purity Ring - Belispeak - Purity Ring", score: "NR", file: "99_Purity_Ring_-_Belispeak_-_Purity_Ring_(youtube).m4a" },
  { id: "100", title: "the craft (portishead glory box ) scorn remix 1994", score: "NR", file: "100_the_craft_(portishead_glory_box_)_scorn_remix_1994_-_musique_cinema_et_série_télévisée_(youtube).m4a" },
  { id: "101", title: "KAIZXKU - Under my skin", score: "NR", file: "101_KAIZXKU_-_Under_my_skin.m4a" },
  { id: "102", title: "MARINA - Bubblegum Bitch", score: "NR", file: "102_Bubblegum_Bitch_(Hardtekk).m4a" },
  { id: "103", title: "Secret Society - Neoperreo (feat. ALIC3E)", score: "NR", file: "103_Secret_Society_-_Neoperreo_(feat._ALIC3E).m4a" },
  { id: "104", title: "Aura (Ultra Slowed)", score: "NR", file: "104_Aura_(Ultra_Slowed).m4a" },
  { id: "105", title: "adore - dancing while the world burns", score: "NR", file: "105_adore_-_dancing_while_the_world_burns.m4a" },
  { id: "106", title: "GRIM LIGHT (Hardtekk)", score: "NR", file: "106_GRIM_LIGHT_(Hardtekk).m4a" },
  { id: "107", title: "TWENTYTHREE - MAKE IT HURT", score: "NR", file: "107_TWENTYTHREE_-_MAKE_IT_HURT.m4a" },
  { id: "108", title: "RECREATE", score: "NR", file: "108_RECREATE.m4a" },
  { id: "109", title: "Ravyn Lenae - Love Me Not best part ultra slowed (Edit by Uhar)", score: "NR", file: "109_Ravyn_Lenae_-_Love_Me_Not_best_part_ultra_slowed_(Edit_by_Uhar).m4a" },
  { id: "110", title: "prodarvee - It Can't Come Quickly Enough Hardstyle", score: "NR", file: "110_prodarvee_-_It_Can't_Come_Quickly_Enough_Hardtekk.m4a" },
  { id: "111", title: "specialsadism hardstyle remix (slowed)", score: "NR", file: "111_specialsadism_hardstyle_remix_(slowed).m4a" },
  { id: "112", title: "OSTBLOCK 3 (SUPER SLOWED + BEST PART) - REKUUDOTEKK", score: "NR", file: "112_OSTBLOCK_3_(SUPER_SLOWED__BEST_PART)_-_REKUUDOTEKK.m4a" },
  { id: "113", title: "VLNCRSH - No Way Out", score: "NR", file: "113_VLNCRSH_-_No_Way_Out.m4a" },
  { id: "114", title: "Neoperreo - Secret Society ft. ALIC3E (Slowed + Reverb)", score: "NR", file: "114_Neoperreo_-_Secret_Society_ft._ALIC3E_(Slowed__Reverb).m4a" },
  { id: "115", title: "Nightcall ft. Dreamhour - Dead V (Official Lyric Video)", score: "NR", file: "115_Nightcall_ft._Dreamhour_-_Dead_V_(Official_Lyric_Video).m4a" },
  { id: "116", title: "wiv - i love u. (sped up + reverb)", score: "NR", file: "116_wiv_-_i_love_u._(sped_up__reverb).m4a" },
  { id: "117", title: "Hot N Cold (hardstyle remix + SUPER SLOWED)", score: "NR", file: "117_Hot_N_Cold_(hardstyle_remix__SUPER_SLOWED).m4a" },
  { id: "118", title: "HOT FREAKS - \"FOR NOTHING\"", score: "NR", file: "118_HOT_FREAKS_-_FOR_NOTHING_(Official_Lyric_Video).mp3" },
  { id: "119", title: "Memories", score: "NR", file: "119_Memories.m4a" },
  { id: "120", title: "QMIIR, NUEKI - TAKA TITI", score: "NR", file: "120_QMIIR,_NUEKI_-_TAKA_TITI.m4a" },
  { id: "121", title: "twilight", score: "NR", file: "121_twilight.mp3" },
  { id: "122", title: "only time", score: "NR", file: "122_only_time.mp3" },
  { id: "123", title: "i dont want your help", score: "NR", file: "123_i_dont_want_your_help.mp3" },
  { id: "124", title: "Dominic Fike - Babydoll", score: "NR", file: "124_Dominic_Fike_-_Babydoll_(Lyrics).mp3" },
  { id: "125", title: "overtonight - spiral song", score: "NR", file: "125_overtonight_-_spiral_song_(official_audio).mp3" },
  { id: "126", title: "iwonnit", score: "NR", file: "126_iwonnit.mp3" },
  { id: "127", title: "unhappy (slowed)", score: "NR", file: "127_unhappy_(slowed).mp3" },
  { id: "128", title: "I can't deny", score: "NR", file: "128_I_can't_deny.mp3" },
  { id: "129", title: "STATUS", score: "NR", file: "129_STATUS.mp3" },
  { id: "130", title: "Trap Life (feat. Ballout)", score: "NR", file: "130_Trap_Life_(feat._Ballout).mp3" },
  { id: "131", title: "Arcade", score: "NR", file: "131_Arcade.mp3" },
  { id: "132", title: "Love Potions X poster boy - 2hollis & bjlips (mashup)", score: "NR", file: "132_Love_Potions_X_poster_boy_-_2hollis_&_bjlips_(mashup).mp3" },
  { id: "133", title: "Illusionary Daytime x 室内系 TrackMaker", score: "NR", file: "133_Illusionary_Daytime_x_室内系_TrackMaker_[Extended_Edit_Version].mp3" },
  { id: "134", title: "NUMBER HARDTEKK (SUPER SLOWED)", score: "NR", file: "134_NUMBER_HARDTEKK_(SUPER_SLOWED).mp3" },
  { id: "135", title: "Trust Nobody", score: "NR", file: "135_Trust_Nobody.mp3" },
  { id: "136", title: "away", score: "NR", file: "136_away.mp3" },
  { id: "137", title: "Ap0LloN - Schachter (Slowed - Best Part)", score: "NR", file: "137_Ap0LloN_-_Schachter_(Slowed_-_Best_Part).mp3" },
  { id: "138", title: "MY JEALOUSY HARDTEKK", score: "NR", file: "138_MY_JEALOUSY_HARDTEKK.mp3" },
  { id: "139", title: "i have no friends", score: "NR", file: "139_i_have_no_friends.mp3" },
  { id: "140", title: "Don't Lose", score: "NR", file: "140_Dont_Lose.mp3" },
  { id: "141", title: "Illusionary Daytime x Trackmaker", score: "NR", file: "141_Illusionary_Daytime_x_Trackmaker.mp3" },
  { id: "142", title: "Катюха", score: "NR", file: "142_Катюха.mp3" },
  { id: "143", title: "I'm Good (Blue) x Stereo Love (slowed + reverb)", score: "NR", file: "143_I'm_Good_(Blue)_x_Stereo_Love_(slowed__reverb).mp3" },
  { id: "144", title: "Sukuna In Shibuya X Glorilla - Yeah Glo (Guitar Remix)", score: "NR", file: "144_Sukuna_In_Shibuya_X_Glorilla_-_Yeah_Glo_(Guitar_Remix).mp3" },
  { id: "145", title: "twentythree - Bite Me", score: "NR", file: "145_Twentythree_-_Bite_Me.mp3" },
  { id: "146", title: "I just banged a snus in canada water", score: "NR", file: "146_I_just_banged_a_snus_in_canada_water.mp3" },
  { id: "148", title: "MY JEALOUSY ULTRA SLOWED + LOW HONOR", score: "NR", file: "148_MY_JEALOUSY_ULTRA_SLOWED__LOW_HONOR.mp3" },
  { id: "149", title: "On The Floor x I Wanna Go", score: "NR", file: "149_On_The_Floor_x_I_Wanna_Go.mp3" },
  { id: "150", title: "Queen St (Slowed + Reverb)", score: "NR", file: "150_Queen_St_(Slowed__Reverb).mp3" },
  { id: "151", title: "SMS", score: "NR", file: "151_SMS.mp3" },
  { id: "151b", title: "Playboi Carti - Long Time (Sanikwave Remix) (slowed and reverb)", score: "NR", file: "151_Playboi_Carti_-_Long_Time_(Sanikwave_Remix)_(slowed_and_reverb).mp3" },
  { id: "152", title: "fake ur face", score: "NR", file: "152_fake_ur_face.mp3" },
  { id: "153", title: "FOR LYFE", score: "NR", file: "153_FOR_LYFE.mp3" },
  { id: "154", title: "Love Potions X Vacation Bible School - Ayesha Erotica & bjlips (mashup)", score: "NR", file: "154_Love_Potions_X_Vacation_Bible_School_-_Ayesha_Erotica_&_bjlips_(mashup).mp3" },
  { id: "155", title: "Pain (Slowed + Reverb)", score: "NR", file: "155_Pain_(Slowed__Reverb).mp3" },
  { id: "156", title: "Kenny Carter - Don't Care", score: "NR", file: "156_kenny_carter_dont_care.mp3" },
  { id: "157", title: "伯虎说 (DJ阳少版)", score: "NR", file: "157_伯虎说 (DJ阳少版).mp3" },
  { id: "158", title: "Person发哥进行曲0.8x", score: "NR", file: "158_Person发哥进行曲0.8x.mp3" },
  { id: "159", title: "有一种期待叫做对方正在输入中", score: "NR", file: "159_有一种期待叫做对方正在输入中.mp3" },
  { id: "160", title: "Max Oazo feat Monessa - Once upon a Time DJ完整版 [李羲承进行曲]", score: "NR", file: "160_Once upon a Time DJ完整版 [李羲承进行曲].mp3" },
  { id: "161", title: "夹心摇", score: "NR", file: "161_夹心摇.mp3" },
  { id: "162", title: "Творческий пиздец", score: "NR", file: "162_Творческий пиздец.mp3" },
  { id: "163", title: "addiction", score: "NR", file: "163_addiction.mp3" },
  { id: "164", title: "Queen St. (Instrumental)", score: "NR", file: "164_Queen St. (Instrumental).mp3" },
  { id: "165", title: "Lightning Moment (纯音乐 Remix) | 米塔的小曲 DJ抖音版 | Instrumental TikTok Remix", score: "NR", file: "165_Lightning Moment (纯音乐 Remix)  米塔的小曲 DJ抖音版  Instrumental TikTok Remix.mp3" },
  { id: "166", title: "Brutal Mog", score: "NR", file: "166_Brutal Mog.mp3" },
  { id: "167", title: "My Destiny (slowed)", score: "NR", file: "167_My Destiny (slowed).mp3" },
  { id: "168", title: "Illusionary Daytime x Trackmaker Slow", score: "NR", file: "168_Illusionary Daytime x Trackmaker Slow.mp3" },
  { id: "169", title: "Help Urself - No Singing", score: "NR", file: "169_Help Urself - No Singing.mp3" },
  { id: "170", title: "FALL FROM THE SKY PT. 2 (Tiktok Remix) (SUPER Slowed + Reverb)", score: "NR", file: "170_FALL FROM THE SKY PT. 2 (Tiktok Remix) (SUPER Slowed  Reverb).mp3" },
  { id: "171", title: "拼凑回忆番", score: "NR", file: "171_拼凑回忆番.mp3" },
  { id: "172", title: "Lil Durk - AHHH HA (INSTRUMENTAL)", score: "NR", file: "172_Lil Durk - AHHH HA (INSTRUMENTAL) Reprod. @WinissBeats.mp3" },
  { id: "173", title: "gott", score: "NR", file: "173_gott.mp3" },
  { id: "174", title: "With God by My Side", score: "NR", file: "174_With God by My Side.mp3" },
  { id: "175", title: "Nelly - Here Comes The Boom (Dekku Remix)", score: "NR", file: "175_Nelly - Here Comes The Boom (Dekku Remix) Super Bowl Special.mp3" },
  { id: "176", title: "любит/ненавидит", score: "NR", file: "176_любитненавидит.mp3" },
  { id: "177", title: "в клубе", score: "NR", file: "177_вклубе.mp3" },
  { id: "178", title: "Pooh Shiesty - At It Again", score: "NR", file: "178_Pooh Shiesty - At It Again (Official Music Video).mp3" },
  { id: "179", title: "falling in love x mylancore/hoodtrap", score: "NR", file: "179_falling in love x mylancorehoodtrap.mp3" },
  { id: "180", title: "#4freestyle", score: "NR", file: "180_4freestyle.mp3" },
  { id: "181", title: "don't care (opium)", score: "NR", file: "181_don't care (opium).mp3" },
];
